// vue-todo/src/components/ListRender.vue
<template>
<div>
  <div>
    <h6 v-for="(item, index) in list" :key="index">{{ item.name }}</h6>
  </div>
  <div>
    <span v-for="(value, key, index) in student" :key="index">
      {{ index }}.{{ key }}: {{ value }}
    </span>
  </div>
</div>
</template>
<script>
export default {
  name: 'ListRender',
  data () {
    return {
      list: [
        {id: 1, name: 'a'},
        {id: 2, name: 'b'}
      ],
      student: {
        name: 'May',
        age: 5,
        sex: 'female'
      }
    }
  }
}
</script>

// react-todo/src/components/ListRender.jsx
import React, { useState } from 'react'

function ListRender() {
  const [list] = useState([
    {id: 1, name: 'a'},
    {id: 2, name: 'b'}
  ])

  const [student] = useState({
    name: 'May',
    age: 5,
    sex: 'female'
  })

  return (
    <div>
      <div>
        {
          list.map((item, index) => <h6 key={index} id={item.id}>{ item.name }</h6>)
        }
      </div>
      <div>
        {
          Object.keys(student).map((key, index) => 
            <span key={index}>{index}.{key}:{student[key]} </span>)
        }
      </div>
      <div>
        {
          Object.entries(student).map((item, index) => {
            const [key, value] = item
            return <span key={index}>{index}.{key}:{value}</span>
          })
        }
      </div>
    </div>
  )
}

export default ListRender
