// vue-todo/src/components/ClassStyle/Index.vue
<template>
  <div>
    <ClassComponent class="border" />
    <StyleComponent />
  </div>
</template>
<script>
import ClassComponent from './ClassComponent'
import StyleComponent from './StyleComponent'
export default {
  name: 'ClassStyle',
  components: { ClassComponent, StyleComponent },
  data () {
    return {}
  }
}
</script>
<style lang="css" scoped>
.border {
  border: 1px solid #999;
}
</style>

// react-todo/src/components/ClassStyle/Index.jsx
import React from 'react'
import ClassComponent from './ClassComponent'
import StyleComponent from './StyleComponent'
class ClassStyle extends React.Component {
  render() {
    return (
      <div>
        <ClassComponent />
        <StyleComponent />
      </div>
    )
  }
}

export default ClassStyle
